import {
  Activity,
  Check,
  Flame,
  CalendarDays,
  Apple,
  Atom,
  Award,
  Backpack,
  Badge,
  Bike,
  BookOpen,
  Box,
  Boxes,
  Brain,
  Briefcase,
  Camera,
  ChartLine,
  Circle,
  Code2,
  Coins,
  Cpu,
  Database,
  Dumbbell,
  Ear,
  Ellipsis,
  Feather,
  Gauge,
  Globe,
  GraduationCap,
  Grid3x3,
  Guitar,
  HandHeart,
  Handshake,
  Heart,
  Home,
  Landmark,
  Lamp,
  Layers,
  LayoutGrid,
  type LucideIcon,
  Map,
  MessageCircle,
  Mic,
  Monitor,
  Moon,
  Music,
  Network,
  Palette,
  PenLine,
  Piano,
  Plug,
  Presentation,
  Puzzle,
  Quote,
  Rocket,
  ScrollText,
  Search,
  Shield,
  Sigma,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Table,
  Target,
  Terminal,
  Truck,
  Type,
  User,
  Users,
  Wallet,
  Waves,
  Workflow,
} from 'lucide-react';

/**
 * Icon registry.
 *
 * Domain records store an icon as a plain string so the data layer never
 * imports React. Everything resolves through here, which also means one place
 * to swap icon sets. Unknown names fall back to a neutral mark rather than
 * throwing.
 */
const REGISTRY: Record<string, LucideIcon> = {
  activity: Activity,
  apple: Apple,
  atom: Atom,
  award: Award,
  backpack: Backpack,
  badge: Badge,
  bank: Landmark,
  bike: Bike,
  book: BookOpen,
  box: Box,
  boxes: Boxes,
  brain: Brain,
  briefcase: Briefcase,
  camera: Camera,
  card: Badge,
  calendar: CalendarDays,
  chart: ChartLine,
  check: Check,
  code: Code2,
  coins: Coins,
  cpp: Code2,
  cpu: Cpu,
  database: Database,
  desktop: Monitor,
  dumbbell: Dumbbell,
  ear: Ear,
  generic: Box,
  globe: Globe,
  graduation: GraduationCap,
  grid: Grid3x3,
  guitar: Guitar,
  handshake: Handshake,
  heart: Heart,
  headphones: Ellipsis,
  home: Home,
  js: Code2,
  lamp: Lamp,
  landmark: Landmark,
  laptop: Monitor,
  layers: Layers,
  layout: LayoutGrid,
  map: Map,
  message: MessageCircle,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  music: Music,
  network: Network,
  palette: Palette,
  pen: PenLine,
  person: User,
  phone: Smartphone,
  piano: Piano,
  pillar: Landmark,
  plug: Plug,
  presentation: Presentation,
  puzzle: Puzzle,
  python: Code2,
  quote: Quote,
  rocket: Rocket,
  scroll: ScrollText,
  search: Search,
  service: HandHeart,
  shield: Shield,
  sigma: Sigma,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  table: Table,
  tablet: Smartphone,
  target: Target,
  terminal: Terminal,
  truck: Truck,
  type: Type,
  users: Users,
  wallet: Wallet,
  waves: Waves,
  workflow: Workflow,
  gauge: Gauge,
  flame: Flame,
};

export function iconFor(name: string | undefined | null): LucideIcon {
  if (!name) return Circle;
  return REGISTRY[name] ?? Circle;
}

/** Names offered in the icon picker when creating domains, branches, nodes. */
export const ICON_CHOICES = Object.keys(REGISTRY).sort();
